# Basic Site settings
title: Kestory's Blog
SEOTitle: xzq的博客 | xzq's Blog
subtitle: Anything for nothing
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: A senior NJU_CSer
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/kestory'}
    # - {title: Resume, description: My CV, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social SNS settings
social:
    weibo: kestory
    github: kestory
    twitter: kestory
    # zhihu:  kestory
    gplus: kestory
    mail: kestoryxu@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
